const STORAGE_KEY = 'finanzas-claras-gastos-v1';
const seed = [
  {id:1, description:'Supermercado', amount:48250, category:'Alimentación', date:'2026-09-02', note:''},
  {id:2, description:'Carga SUBE', amount:12500, category:'Transporte', date:'2026-09-03', note:''},
  {id:3, description:'Alquiler', amount:310000, category:'Vivienda y servicios', date:'2026-09-01', note:'Septiembre'},
  {id:4, description:'Café y medialunas', amount:6800, category:'Alimentación', date:'2026-09-04', note:''},
  {id:5, description:'Farmacia', amount:18700, category:'Salud', date:'2026-09-05', note:''}
];
let expenses = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null') || seed;
let selectedReceipt = null;
let selectedReceiptFile = null;
let cameraStream = null;
const $ = id => document.getElementById(id);
const money = value => new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(value);
const dateLabel = value => new Intl.DateTimeFormat('es-AR',{day:'2-digit',month:'short'}).format(new Date(`${value}T12:00:00`)).replace('.','');
const currentMonth = () => $('month-picker').value || new Date().toISOString().slice(0,7);
function save(){localStorage.setItem(STORAGE_KEY, JSON.stringify(expenses));}
function render(){
  const month=currentMonth(), search=($('search').value||'').toLowerCase();
  const monthExpenses=expenses.filter(e=>e.date.startsWith(month));
  const visible=monthExpenses.filter(e=>`${e.description} ${e.category} ${e.note}`.toLowerCase().includes(search)).sort((a,b)=>b.date.localeCompare(a.date));
  const total=monthExpenses.reduce((s,e)=>s+Number(e.amount),0);
  $('total-spent').textContent=money(total); $('chart-total').textContent=money(total); $('movement-count').textContent=monthExpenses.length;
  const grouped=monthExpenses.reduce((acc,e)=>(acc[e.category]=(acc[e.category]||0)+Number(e.amount),acc),{});
  const categories=Object.entries(grouped).sort((a,b)=>b[1]-a[1]); const top=categories[0];
  $('top-category').textContent=top?top[0]:'—'; $('top-category-value').textContent=top?`${money(top[1])} en este período`:'Sin movimientos todavía';
  $('comparison').textContent=total?'Período seleccionado':'Agregá un gasto para comenzar';
  $('category-chart').innerHTML=categories.map(([name,value])=>`<div class="bar-line"><span>${name}</span><div class="bar-track"><div class="bar" style="width:${Math.max(4,(value/(top?.[1]||1))*100)}%"></div></div><span class="bar-value">${money(value)}</span></div>`).join('');
  $('chart-empty').style.display=categories.length?'none':'block';
  $('expense-table').innerHTML=visible.map(e=>`<tr><td>${escapeHtml(e.description)}${e.note?`<small class="muted"> · ${escapeHtml(e.note)}</small>`:''}${e.receipt?`<small class="muted"> · 📎 ${escapeHtml(e.receipt.name)}</small>`:''}</td><td><span class="category-pill">${escapeHtml(e.category)}</span></td><td>${dateLabel(e.date)}</td><td class="align-right">${money(e.amount)}</td><td class="align-right"><button class="delete-btn" data-id="${e.id}" title="Eliminar gasto" aria-label="Eliminar ${escapeHtml(e.description)}">×</button></td></tr>`).join('');
  $('table-empty').classList.toggle('hidden',visible.length>0);
}
function escapeHtml(text){return String(text).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function setDefaults(){const now=new Date(); $('month-picker').value=now.toISOString().slice(0,7); $('date').value=now.toISOString().slice(0,10);}
function handleReceipt(file){if(!file)return;selectedReceiptFile=file;selectedReceipt={name:file.name,type:file.type||'archivo',size:file.size};$('attachment-status').textContent=file.type==='application/pdf'?'PDF listo para analizar':'Imagen lista para analizar';$('analyze-btn').disabled=false;$('attachment-preview').classList.remove('hidden');$('attachment-preview').innerHTML=`<span class="receipt-name">📎 ${escapeHtml(file.name)}<small>${file.type==='application/pdf'?'Documento PDF':'Imagen'} · ${(file.size/1024).toFixed(0)} KB</small></span><button type="button" id="remove-attachment" aria-label="Quitar comprobante">×</button>`;$('remove-attachment').addEventListener('click',clearReceipt);}
function clearReceipt(){selectedReceipt=null;selectedReceiptFile=null;$('receipt-file').value='';$('receipt-camera').value='';$('analyze-btn').disabled=true;$('analysis-result').classList.add('hidden');$('analysis-result').innerHTML='';$('attachment-preview').classList.add('hidden');$('attachment-preview').innerHTML='';$('attachment-status').textContent='Podés adjuntar una foto o un PDF';}
$('receipt-file').addEventListener('change',event=>handleReceipt(event.target.files[0]));$('receipt-camera').addEventListener('change',event=>handleReceipt(event.target.files[0]));
function closeCamera(){if(cameraStream){cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null;}$('camera-video').srcObject=null;$('camera-modal').classList.add('hidden');}
$('open-camera-btn').addEventListener('click',async()=>{if(!navigator.mediaDevices?.getUserMedia){$('receipt-camera').click();return;}try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('camera-video').srcObject=cameraStream;$('camera-modal').classList.remove('hidden');}catch(error){$('receipt-camera').click();$('attachment-status').textContent='No se pudo abrir la cámara; elegí una imagen';}});
$('close-camera-btn').addEventListener('click',closeCamera);$('cancel-camera-btn').addEventListener('click',closeCamera);
$('take-photo-btn').addEventListener('click',()=>{const video=$('camera-video'),canvas=$('camera-canvas');if(!video.videoWidth)return;canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{const file=new File([blob],`comprobante_camara_${Date.now()}.jpg`,{type:'image/jpeg'});handleReceipt(file);closeCamera();},'image/jpeg',.9);});
function applyAnalysis(result){const fields=result.campos||{};if(fields.comercio_destinatario&&fields.comercio_destinatario!=='Sin dato')$('description').value=fields.comercio_destinatario;if(typeof fields.importe==='number')$('amount').value=fields.importe;if(fields.fecha&&/^\d{4}-\d{2}-\d{2}$/.test(fields.fecha))$('date').value=fields.fecha;if(fields.categoria&&[...$('category').options].some(option=>option.value===fields.categoria))$('category').value=fields.categoria;if(fields.comentario&&fields.comentario!=='Sin dato')$('note').value=fields.comentario;const observations=(result.observaciones||[]).map(escapeHtml).join('<br>');const questions=(result.preguntas||[]).map(escapeHtml).join('<br>');$('analysis-result').innerHTML=`<strong>${result.estado==='listo'?'Análisis listo para revisar':'Requiere revisión'}</strong>${observations?`<small>${observations}</small>`:''}${questions?`<small>Preguntas: ${questions}</small>`:''}`;$('analysis-result').classList.remove('hidden');}
$('analyze-btn').addEventListener('click',async()=>{if(!selectedReceiptFile)return;const button=$('analyze-btn');button.disabled=true;button.textContent='Analizando…';$('analysis-result').classList.remove('hidden');$('analysis-result').textContent='El agente está leyendo el comprobante…';try{const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(selectedReceiptFile);});const response=await fetch('/api/analyze-receipt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:selectedReceiptFile.name,mime_type:selectedReceiptFile.type,data:dataUrl.split(',')[1]})});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error||'No se pudo analizar el comprobante.');applyAnalysis(payload.result);$('attachment-status').textContent='Análisis completado · revisá los campos';}catch(error){$('analysis-result').innerHTML=`<strong>No se pudo analizar</strong><small>${escapeHtml(error.message)}. Verificá que el servidor esté iniciado y que OPENAI_API_KEY esté configurada.</small>`;}finally{button.disabled=false;button.textContent='✦ Analizar comprobante';}});
function setSaveStatus(message,error=false){$('save-status').textContent=message;$('save-status').classList.remove('hidden');$('save-status').classList.toggle('error',error);}
function waitForGoogleAuth(){return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{window.removeEventListener('message',onMessage);reject(new Error('La ventana de Google no confirmó la autorización.'));},180000);function onMessage(event){if(event.origin!==window.location.origin||event.data?.type!=='google-auth-complete')return;clearTimeout(timeout);window.removeEventListener('message',onMessage);resolve();}window.addEventListener('message',onMessage);});}
async function authorizeAndSave(sheetUrl,expense){const popup=window.open('about:blank','google-auth','width=520,height=720');if(!popup)throw new Error('El navegador bloqueó la ventana de autenticación. Permití ventanas emergentes para este sitio.');const authResponse=await fetch('/api/google-auth-url');const authData=await authResponse.json();if(!authResponse.ok||!authData.ok)throw new Error(authData.error||'No se pudo iniciar la autenticación de Google.');popup.location=authData.auth_url;setSaveStatus('Autorizá el acceso en la ventana de Google…');await waitForGoogleAuth();setSaveStatus('Guardando en Google Sheets…');const response=await fetch('/api/google-save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sheet_url:sheetUrl,expense})});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Google Sheets no pudo guardar el gasto.');return result;}
$('expense-form').addEventListener('submit',async event=>{event.preventDefault();if(!event.target.reportValidity())return;const data=new FormData(event.target),expense={description:data.get('description').trim(),amount:Number(data.get('amount')),category:data.get('category'),date:data.get('date'),note:data.get('note').trim(),currency:'ARS',cbu:'Sin dato',payment_method:'Sin dato',receipt:selectedReceipt};const button=event.target.querySelector('button[type="submit"]');button.disabled=true;try{await authorizeAndSave(data.get('sheet_url').trim(),expense);expenses.push({id:Date.now(),...expense});save();event.target.reset();clearReceipt();$('date').value=$('month-picker').value+'-01';$('save-status').classList.add('hidden');render();}catch(error){setSaveStatus(error.message,true);}finally{button.disabled=false;}});
$('month-picker').addEventListener('change',render); $('search').addEventListener('input',render);
$('expense-table').addEventListener('click',event=>{const btn=event.target.closest('[data-id]');if(!btn)return;expenses=expenses.filter(e=>e.id!==Number(btn.dataset.id));save();render();});
$('export-btn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(expenses.filter(e=>e.date.startsWith(currentMonth())),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`gastos_${currentMonth()}.json`;a.click();URL.revokeObjectURL(url);});
setDefaults();render();
