const STORAGE_KEY = 'finanzas-claras-gastos-v2';
localStorage.removeItem('finanzas-claras-gastos-v1');
localStorage.removeItem('finanzas-claras-destination-id');
const seed = [];
let expenses = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null') || seed;
let selectedReceipts = [];
let selectedReceiptFiles = [];
let batchResults = [];
let sheetSelectionResolve = null;
let cameraStream = null;
const $ = id => document.getElementById(id);
const money = value => new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(value);
const dateLabel = value => new Intl.DateTimeFormat('es-AR',{day:'2-digit',month:'short'}).format(new Date(`${value}T12:00:00`)).replace('.','');
const currentMonth = () => $('month-picker').value || new Date().toISOString().slice(0,7);
const chartColors=['#2c7653','#ed8167','#4d8bc7','#e3a83b','#9569b5','#4aa7a1','#d35f77','#7b8f63','#c47f48','#6674a8'];
function save(){localStorage.setItem(STORAGE_KEY, JSON.stringify(expenses));}
function render(){
  const month=currentMonth(), search=($('search').value||'').toLowerCase();
  const monthExpenses=expenses.filter(e=>e.date.startsWith(month));
  const visible=monthExpenses.filter(e=>`${e.description} ${e.category} ${e.note}`.toLowerCase().includes(search)).sort((a,b)=>b.date.localeCompare(a.date));
  const total=monthExpenses.reduce((s,e)=>s+Number(e.amount),0);
  $('total-spent').textContent=money(total); $('chart-total').textContent=money(total); $('movement-count').textContent=monthExpenses.length;
  const grouped=monthExpenses.reduce((acc,e)=>(acc[e.category]=(acc[e.category]||0)+Number(e.amount),acc),{});
  const categories=Object.entries(grouped).sort((a,b)=>b[1]-a[1]); const top=categories[0];
  $('top-category').textContent=top?top[0]:'—'; $('top-category-value').textContent=top?`${money(top[1])} en este período`:'Sin movimientos todavía';
  $('comparison').textContent=total?'Período seleccionado':'Agregá un gasto para comenzar';
  $('category-chart').innerHTML=categories.map(([name,value])=>`<div class="bar-line"><span>${name}</span><div class="bar-track"><div class="bar" style="width:${Math.max(4,(value/(top?.[1]||1))*100)}%"></div></div><span class="bar-value">${money(value)}</span></div>`).join('');
  $('chart-empty').style.display=categories.length?'none':'block';
  $('expense-table').innerHTML=visible.map(e=>`<tr><td>${escapeHtml(e.description)}${e.note?`<small class="muted"> · ${escapeHtml(e.note)}</small>`:''}${e.receipt?`<small class="muted"> · 📎 ${escapeHtml(e.receipt.name)}</small>`:''}</td><td><span class="category-pill">${escapeHtml(e.category)}</span></td><td>${dateLabel(e.date)}</td><td class="align-right">${money(e.amount)}</td><td class="align-right"><button class="delete-btn" data-id="${e.id}" title="Eliminar gasto" aria-label="Eliminar ${escapeHtml(e.description)}">×</button></td></tr>`).join('');
  $('table-empty').classList.toggle('hidden',visible.length>0);
  renderCharts();
}
function monthRange(start,end){const result=[];let cursor=new Date(`${start}-01T12:00:00`),limit=new Date(`${end}-01T12:00:00`);while(cursor<=limit&&result.length<120){result.push(cursor.toISOString().slice(0,7));cursor.setMonth(cursor.getMonth()+1);}return result;}
function renderCharts(){const current=expenses.filter(e=>e.date.startsWith(currentMonth()));const totals=current.reduce((acc,e)=>(acc[e.category]=(acc[e.category]||0)+Number(e.amount||0),acc),{});const entries=Object.entries(totals).sort((a,b)=>b[1]-a[1]);const sum=entries.reduce((n,item)=>n+item[1],0);let angle=0;const stops=entries.map(([name,value],index)=>{const start=angle;angle+=sum?value/sum*360:0;return `${chartColors[index%chartColors.length]} ${start}deg ${angle}deg`;});$('pie-chart').style.background=entries.length?`conic-gradient(${stops.join(',')})`:'conic-gradient(#dfe8e2 0 360deg)';$('pie-legend').innerHTML=entries.map(([name,value],index)=>`<div class="legend-item"><i class="legend-dot" style="background:${chartColors[index%chartColors.length]}"></i><span>${escapeHtml(name)} · ${sum?Math.round(value/sum*100):0}%</span></div>`).join('')||'<span class="picker-help">No hay datos para este mes.</span>';const start=$('graph-start').value||currentMonth(),end=$('graph-end').value||currentMonth();const range=monthRange(start<=end?start:end,start<=end?end:start);const inRange=expenses.filter(e=>e.date.slice(0,7)>=range[0]&&e.date.slice(0,7)<=range[range.length-1]);const cats=[...new Set(inRange.map(e=>e.category).filter(Boolean))].sort();if(!selectedChartCategories.size)cats.forEach(cat=>selectedChartCategories.add(cat));selectedChartCategories.forEach(cat=>{if(!cats.includes(cat))selectedChartCategories.delete(cat);});$('category-filters').innerHTML=cats.map(cat=>`<label><input type="checkbox" value="${escapeHtml(cat)}" ${selectedChartCategories.has(cat)?'checked':''}>${escapeHtml(cat)}</label>`).join('')||'<span class="picker-help">Importá una planilla para ver datos.</span>';drawTimeline(range,inRange,cats);}
let selectedChartCategories=new Set();
let destinationSpreadsheetId=localStorage.getItem('finanzas-claras-destination-id')||'';
function drawTimeline(months,items,cats){const canvas=$('timeline-chart'),ratio=window.devicePixelRatio||1,width=canvas.clientWidth||600,height=260;canvas.width=width*ratio;canvas.height=height*ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);ctx.clearRect(0,0,width,height);if(!months.length)return;const selected=cats.filter(cat=>selectedChartCategories.has(cat));const mode=document.querySelector('input[name="chart-mode"]:checked')?.value||'total';const series=mode==='total'?['Seleccionados']:selected;const values=series.map((name)=>months.map(month=>items.filter(e=>e.date.startsWith(month)&&(name==='Seleccionados'?selected.includes(e.category):e.category===name)).reduce((sum,e)=>sum+Number(e.amount||0),0)));const max=Math.max(1,...values.flat());const left=45,right=15,top=16,bottom=38,plotW=width-left-right,plotH=height-top-bottom;ctx.font='11px DM Sans';ctx.strokeStyle='#dfe8e2';ctx.fillStyle='#718078';ctx.lineWidth=1;for(let i=0;i<=4;i++){const y=top+plotH-(plotH*i/4);ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(width-right,y);ctx.stroke();ctx.fillText(money(max*i/4),2,y+4);}months.forEach((month,index)=>{const x=left+(months.length===1?plotW/2:plotW*index/(months.length-1));ctx.fillText(month.slice(5),x-10,height-13);});series.forEach((name,seriesIndex)=>{ctx.strokeStyle=chartColors[seriesIndex%chartColors.length];ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=2;ctx.beginPath();values[seriesIndex].forEach((value,index)=>{const x=left+(months.length===1?plotW/2:plotW*index/(months.length-1)),y=top+plotH-(value/max)*plotH;if(index===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();values[seriesIndex].forEach((value,index)=>{const x=left+(months.length===1?plotW/2:plotW*index/(months.length-1)),y=top+plotH-(value/max)*plotH;ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill();});});}
function escapeHtml(text){return String(text).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function setDefaults(){const now=new Date();$('month-picker').value=now.toISOString().slice(0,7);$('date').value=now.toISOString().slice(0,10);$('graph-start').value=new Date(now.getFullYear(),now.getMonth()-5,1).toISOString().slice(0,7);$('graph-end').value=now.toISOString().slice(0,7);}
function handleReceipts(files){const incoming=Array.from(files||[]);if(!incoming.length)return;const combined=[...selectedReceiptFiles,...incoming].slice(0,10);selectedReceiptFiles=combined;selectedReceipts=combined.map(file=>({name:file.name,type:file.type||'archivo',size:file.size}));batchResults=[];$('attachment-status').textContent=`${selectedReceiptFiles.length} comprobante${selectedReceiptFiles.length===1?'':'s'} seleccionado${selectedReceiptFiles.length===1?'':'s'}`;$('analyze-btn').disabled=false;$('attachment-preview').classList.remove('hidden');$('attachment-preview').innerHTML=`<span class="receipt-name">📎 ${selectedReceipts.map(file=>escapeHtml(file.name)).join('<br>')}<small>Se analizarán en lote · máximo 10</small></span><button type="button" id="remove-attachment" aria-label="Quitar comprobantes">×</button>`;$('remove-attachment').addEventListener('click',clearReceipt);}
function clearReceipt(){selectedReceipts=[];selectedReceiptFiles=[];batchResults=[];$('receipt-file').value='';$('receipt-camera').value='';$('analyze-btn').disabled=true;$('analysis-result').classList.add('hidden');$('analysis-result').innerHTML='';$('attachment-preview').classList.add('hidden');$('attachment-preview').innerHTML='';$('attachment-status').textContent='Podés seleccionar varias imágenes o PDF';}
$('receipt-file').addEventListener('change',event=>handleReceipts(event.target.files));$('receipt-camera').addEventListener('change',event=>handleReceipts(event.target.files));
function closeCamera(){if(cameraStream){cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null;}$('camera-video').srcObject=null;$('camera-modal').classList.add('hidden');}
$('open-camera-btn').addEventListener('click',async()=>{if(!navigator.mediaDevices?.getUserMedia){$('receipt-camera').click();return;}try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('camera-video').srcObject=cameraStream;$('camera-modal').classList.remove('hidden');}catch(error){$('receipt-camera').click();$('attachment-status').textContent='No se pudo abrir la cámara; elegí una imagen';}});
$('close-camera-btn').addEventListener('click',closeCamera);$('cancel-camera-btn').addEventListener('click',closeCamera);
$('take-photo-btn').addEventListener('click',()=>{const video=$('camera-video'),canvas=$('camera-canvas');if(!video.videoWidth)return;canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{const file=new File([blob],`comprobante_camara_${Date.now()}.jpg`,{type:'image/jpeg'});handleReceipts([file]);closeCamera();},'image/jpeg',.9);});
function applyBatchAnalysis(results){batchResults=results;const first=results[0]?.campos||{};if(first.comercio_destinatario&&first.comercio_destinatario!=='Sin dato')$('description').value=first.comercio_destinatario;if(typeof first.importe==='number')$('amount').value=first.importe;if(first.fecha&&/^\d{4}-\d{2}-\d{2}$/.test(first.fecha))$('date').value=first.fecha;if(first.categoria&&[...$('category').options].some(option=>option.value===first.categoria))$('category').value=first.categoria;if(first.comentario&&first.comentario!=='Sin dato')$('note').value=first.comentario;const cards=results.map((result,index)=>{const fields=result.campos||{};const observations=(result.observaciones||[]).map(escapeHtml).join(' · ');const questions=(result.preguntas||[]).map(escapeHtml).join(' · ');const value=(field,fallback='')=>escapeHtml(fields[field]??fallback);return `<fieldset class="review-card"><legend>${index+1}. ${escapeHtml(result.archivo||'comprobante')}</legend><div class="review-grid"><label>Comercio<input data-review="description" data-index="${index}" value="${value('comercio_destinatario')}" placeholder="Sin dato"></label><label>Importe<input data-review="amount" data-index="${index}" type="number" min="0" step="0.01" value="${value('importe')}" placeholder="0"></label><label>Fecha<input data-review="date" data-index="${index}" type="date" value="${/^\d{4}-\d{2}-\d{2}$/.test(fields.fecha||'')?value('fecha'):''}"></label><label>Moneda<input data-review="currency" data-index="${index}" value="${value('moneda','ARS')}"></label><label>Categoría<input data-review="category" data-index="${index}" value="${value('categoria')}" placeholder="Otros"></label><label>Medio de pago<input data-review="payment_method" data-index="${index}" value="${value('medio_pago')}" placeholder="Sin dato"></label><label>CBU destino<input data-review="cbu" data-index="${index}" value="${value('cbu_destino')}" placeholder="Sin dato"></label><label>Comentario<input data-review="note" data-index="${index}" value="${value('comentario')}"></label></div><small>${result.estado==='listo'?'Listo para revisar':'Requiere revisión'}${observations?` · ${observations}`:''}${questions?` · Preguntas: ${questions}`:''}</small></fieldset>`;}).join('');$('analysis-result').innerHTML=`<strong>${results.length} comprobante${results.length===1?'':'s'} analizado${results.length===1?'':'s'}</strong><p class="review-help">Revisá y corregí los campos antes de guardar en Google Sheets. Los cambios se aplicarán a cada comprobante.</p><div class="review-list">${cards}</div>`;$('analysis-result').classList.remove('hidden');}
function reviewedBatch(){return batchResults.map((result,index)=>{const get=name=>document.querySelector(`[data-review="${name}"][data-index="${index}"]`)?.value.trim()||'';const amount=Number(get('amount'));return {description:get('description'),amount:Number.isFinite(amount)?amount:0,date:get('date'),note:get('note'),currency:get('currency')||'ARS',cbu:get('cbu')||'Sin dato',payment_method:get('payment_method')||'Sin dato',category:get('category')||'Otros',receipt:{name:result.archivo||'comprobante'}};});}
$('analyze-btn').addEventListener('click',async()=>{if(!selectedReceiptFiles.length)return;const button=$('analyze-btn');button.disabled=true;button.textContent='Analizando lote…';$('analysis-result').classList.remove('hidden');$('analysis-result').textContent=`El agente está leyendo ${selectedReceiptFiles.length} comprobante${selectedReceiptFiles.length===1?'':'s'}…`;try{const documents=await Promise.all(selectedReceiptFiles.map(file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({filename:file.name,mime_type:file.type,data:reader.result.split(',')[1]});reader.onerror=reject;reader.readAsDataURL(file);})));const response=await fetch('/api/analyze-receipts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({documents})});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error||'No se pudo analizar el lote.');applyBatchAnalysis(payload.results);$('attachment-status').textContent=`${payload.count} análisis completados · revisá los campos`;}catch(error){$('analysis-result').innerHTML=`<strong>No se pudo analizar el lote</strong><small>${escapeHtml(error.message)}. Verificá que el servidor esté iniciado y que OPENAI_API_KEY esté configurada.</small>`;}finally{button.disabled=false;button.textContent='✦ Analizar comprobantes';}});
function setSaveStatus(message,error=false){$('save-status').textContent=message;$('save-status').classList.remove('hidden');$('save-status').classList.toggle('error',error);}
function waitForGoogleAuth(){return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{window.removeEventListener('message',onMessage);reject(new Error('La ventana de Google no confirmó la autorización.'));},180000);function onMessage(event){if(event.origin!==window.location.origin||event.data?.type!=='google-auth-complete')return;clearTimeout(timeout);window.removeEventListener('message',onMessage);resolve();}window.addEventListener('message',onMessage);});}
function chooseSheet(files){return new Promise((resolve,reject)=>{sheetSelectionResolve=resolve;$('sheet-list').innerHTML=files.length?files.map(file=>`<button class="sheet-option" type="button" data-sheet-id="${escapeHtml(file.id)}"><strong>▣ ${escapeHtml(file.name)}</strong><small>Modificada: ${file.modifiedTime?new Date(file.modifiedTime).toLocaleString('es-AR'): 'sin fecha'}</small></button>`).join(''):'<p class="picker-help">No se encontraron planillas disponibles.</p>';$('sheet-picker-modal').classList.remove('hidden');if(!files.length)reject(new Error('No se encontraron planillas de Google Sheets.'));});}
function closeSheetPicker(){if(sheetSelectionResolve){sheetSelectionResolve(null);sheetSelectionResolve=null;}$('sheet-picker-modal').classList.add('hidden');}
$('sheet-list').addEventListener('click',event=>{const option=event.target.closest('[data-sheet-id]');if(!option||!sheetSelectionResolve)return;const id=option.dataset.sheetId;sheetSelectionResolve(id);sheetSelectionResolve=null;$('sheet-picker-modal').classList.add('hidden');});$('close-sheet-picker').addEventListener('click',closeSheetPicker);
async function authorizeAndSave(sheetUrl,expensesBatch){const popup=window.open('about:blank','google-auth','width=520,height=720');if(!popup)throw new Error('El navegador bloqueó la ventana de autenticación. Permití ventanas emergentes para este sitio.');const authResponse=await fetch('/api/google-auth-url');const authData=await authResponse.json();if(!authResponse.ok||!authData.ok)throw new Error(authData.error||'No se pudo iniciar la autenticación de Google.');popup.location=authData.auth_url;setSaveStatus('Autorizá el acceso en la ventana de Google…');await waitForGoogleAuth();let spreadsheetId='';if(sheetUrl){spreadsheetId=sheetUrl;}else if(destinationSpreadsheetId){spreadsheetId=destinationSpreadsheetId;}else{setSaveStatus('Creando tu carpeta y planilla de gastos…');const setupResponse=await fetch('/api/google-setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({spreadsheet_name:$('sheet-name').value.trim()||'Gastos personales'})});const setupData=await setupResponse.json();if(!setupResponse.ok||!setupData.ok)throw new Error(setupData.error||'No se pudo crear la carpeta y la planilla.');spreadsheetId=setupData.workspace.spreadsheet_id;destinationSpreadsheetId=spreadsheetId;localStorage.setItem('finanzas-claras-destination-id',spreadsheetId);$('sheet-name').value=setupData.workspace.spreadsheet_name;}setSaveStatus(`Guardando ${expensesBatch.length} registro${expensesBatch.length===1?'':'s'} en Google Sheets…`);const body={expenses:expensesBatch};if(sheetUrl)body.sheet_url=spreadsheetId;else body.spreadsheet_id=spreadsheetId;const response=await fetch('/api/google-save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Google Sheets no pudo guardar el lote.');return result;}
function rowsToExpenses(rows){const first=(rows[0]||[]).map(value=>String(value).toLowerCase().trim());const hasHeader=first.some(value=>['fecha','importe','categoria','categoría','comercio_destinatario'].includes(value));const dataRows=hasHeader?rows.slice(1):rows;return dataRows.filter(row=>row.some(Boolean)).map(row=>{const rawAmount=String(row[1]||'').replace(/[^0-9,.-]/g,'').trim();const normalized=rawAmount.includes(',')?rawAmount.replace(/\./g,'').replace(',','.'):rawAmount.replace(/,/g,'');return {id:Date.now()+Math.random(),date:row[0]||'',amount:Number(normalized)||0,currency:row[2]||'ARS',description:row[3]||'',cbu:row[4]||'Sin dato',payment_method:row[5]||'Sin dato',category:row[6]||'Otros',note:row[7]||'',receipt:null};});}
async function importFromGoogleSheet(){const popup=window.open('about:blank','google-auth','width=520,height=720');if(!popup)throw new Error('El navegador bloqueó la ventana de autenticación.');const authResponse=await fetch('/api/google-auth-url');const authData=await authResponse.json();if(!authResponse.ok||!authData.ok)throw new Error(authData.error||'No se pudo iniciar la autenticación de Google.');popup.location=authData.auth_url;setSaveStatus('Autorizá el acceso en la ventana de Google…');await waitForGoogleAuth();const filesResponse=await fetch('/api/google-files');const filesData=await filesResponse.json();if(!filesResponse.ok||!filesData.ok)throw new Error(filesData.error||'No se pudieron buscar tus planillas.');const spreadsheetId=await chooseSheet(filesData.files);if(!spreadsheetId)throw new Error('No seleccionaste una planilla.');setSaveStatus('Leyendo gastos de la planilla…');const response=await fetch(`/api/google-read?spreadsheet_id=${encodeURIComponent(spreadsheetId)}`);const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'No se pudo leer la planilla.');const imported=rowsToExpenses(result.data.values||[]);expenses=imported;destinationSpreadsheetId=spreadsheetId;localStorage.setItem('finanzas-claras-destination-id',spreadsheetId);save();render();setSaveStatus(`${imported.length} gastos importados y gráficos actualizados.`);}
$('import-sheet-btn').addEventListener('click',async()=>{try{await importFromGoogleSheet();}catch(error){setSaveStatus(error.message,true);}});
 $('expense-form').addEventListener('submit',async event=>{event.preventDefault();if(!event.target.reportValidity())return;const data=new FormData(event.target);const manualExpense={description:data.get('description').trim(),amount:Number(data.get('amount')),category:data.get('category'),date:data.get('date'),note:data.get('note').trim(),currency:'ARS',cbu:'Sin dato',payment_method:'Sin dato',receipt:selectedReceipts[0]||null};const expensesBatch=batchResults.length?reviewedBatch():[manualExpense];if(batchResults.length&&expensesBatch.some(expense=>!expense.description||!expense.date||expense.amount<=0)){setSaveStatus('Revisá comercio, importe y fecha en todos los comprobantes antes de guardar.',true);return;}const button=event.target.querySelector('button[type="submit"]');button.disabled=true;try{await authorizeAndSave(data.get('sheet_url').trim(),expensesBatch);expenses.push(...expensesBatch.map(expense=>({id:Date.now()+Math.random(),...expense})));save();event.target.reset();clearReceipt();$('date').value=$('month-picker').value+'-01';$('save-status').classList.add('hidden');render();}catch(error){setSaveStatus(error.message,true);}finally{button.disabled=false;}});
$('month-picker').addEventListener('change',render); $('search').addEventListener('input',render);
$('graph-start').addEventListener('change',renderCharts);$('graph-end').addEventListener('change',renderCharts);document.querySelectorAll('input[name="chart-mode"]').forEach(input=>input.addEventListener('change',renderCharts));$('category-filters').addEventListener('change',event=>{if(event.target.matches('input[type="checkbox"]')){if(event.target.checked)selectedChartCategories.add(event.target.value);else selectedChartCategories.delete(event.target.value);renderCharts();}});window.addEventListener('resize',renderCharts);
$('import-btn').addEventListener('click',()=>$('import-file').click());$('import-file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{const parsed=JSON.parse(await file.text());const imported=Array.isArray(parsed)?parsed:(parsed.expenses||parsed.gastos||parsed.registros||[]);if(!Array.isArray(imported)||!imported.length)throw new Error('El archivo no contiene una lista de gastos.');const normalized=imported.map(item=>({id:Date.now()+Math.random(),description:item.description||item.comercio_destinatario||item.comercio||'',amount:Number(item.amount??item.importe??0),category:item.category||item.categoria||'Otros',date:item.date||item.fecha||new Date().toISOString().slice(0,10),note:item.note||item.comentario||'',currency:item.currency||item.moneda||'ARS',receipt:item.receipt||null}));expenses.push(...normalized);save();render();setSaveStatus(`${normalized.length} gasto${normalized.length===1?'':'s'} importado${normalized.length===1?'':'s'} correctamente.`);}catch(error){setSaveStatus(error.message,true);}finally{event.target.value='';}});
$('expense-table').addEventListener('click',event=>{const btn=event.target.closest('[data-id]');if(!btn)return;expenses=expenses.filter(e=>e.id!==Number(btn.dataset.id));save();render();});
$('export-btn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(expenses.filter(e=>e.date.startsWith(currentMonth())),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`gastos_${currentMonth()}.json`;a.click();URL.revokeObjectURL(url);});
setDefaults();render();
